apiVersion: v1
kind: Pod
metadata:
  name: resources-demo
specs:
  containers:
    - name: demo-container
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"